### ISSUE TITLE
Customize login page

### ISSUE THREAD

**Issue by jmarkfen** [BSIT-Caprock/Barangay-System#80]
https://tapansharma.dev/blog/a-guide-to-override-the-default-login-behavior-in-filamentphp

**Comment by jmarkfen** [comment]
Write suggestions for what the login page should look like.

**Comment by hazelr-pontilla** [comment]
Suggestions:

- having a welcome text to the user
- adding the introductory about the system
- (optional) credits

**Comment by maridanne** [comment]
- signup
- forgot password
